animations {
    enabled = yes

    # curvas suaves
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = fluent, 0.2, 0.8, 0.2, 1
    bezier = overshot, 0.13, 0.99, 0.29, 1.1

    # ventanas
    animation = windows, 1, 7, overshot, popin 87%
    animation = windowsIn, 1, 7, overshot, popin 87%
    animation = windowsOut, 1, 6, smoothOut, popin 87%

    # fade
    animation = fade, 1, 6, smoothIn
    animation = fadeIn, 1, 5, smoothIn
    animation = fadeOut, 1, 5, smoothOut

    # bordes
    animation = border, 1, 10, fluent

    # workspaces
    animation = workspaces, 1, 7, fluent, slidefadevert 25%

    # capas
    animation = layers, 1, 6, fluent

    # especiales (lo dejamos pero más consistente)
    animation = specialWorkspace, 1, 7, overshot, slidefadevert 25%
}