#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = sleep 3 && waybar
exec-once = swaync
exec-once = hypridle
exec-once = hyprshade on purple
exec-once = ~/.config/hypr/scripts/window-sound.sh
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = eww daemon
exec-once = sleep 4 && eww open dashboard
exec-once = sleep 2 && mpvpaper -o "no-audio loop" '*' ~/.config/wallpaper/mov/Nissan-Skyline.mp4 &
#exec-once = ~/.config/hypr/scripts/wallcycle.sh
# exec-once = hyprpaper
# exec-once = sleep 2 && hyprctl hyprpaper preload $HOME/.config/wallpaper/fondo2.png
# exec-once = sleep 2 && hyprctl hyprpaper wallpaper ",$HOME/.config/wallpaper/fondo2.png"
# exec-once = sleep 6 && eww reload
exec-once = sleep 3 && pkill blueman-applet
