
# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2

    col.active_border = rgb(9d4edd)
    col.inactive_border = rgb(2a2a2a)

    layout = dwindle
}
