general {
    disable_loading_bar = false
    hide_cursor = false
    grace = 10
    no_fade_in = false
}

background {
    monitor =
    path = /home/bytemonster/Wallpaper/lock.jpg
    blur_passes = 4
    blur_size = 8
    noise = 0.0117
    contrast = 1.2
    brightness = 0.85
    vibrancy = 0.25
    vibrancy_darkness = 0.15
}

# Hora principal
label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M:%S')"
    color = rgba(8af7dfff)
    font_size = 74
    font_family = Hack
    position = 0, 220
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
}

# Fecha
label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d de %B %Y')"
    color = rgba(c8fff5dd)
    font_size = 22
    font_family = Hack
    position = 0, 155
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
}

# Texto estilo sistema
label {
    monitor =
    text = 󰌾 ACCESS SECURED
    color = rgba(00ffbbee)
    font_size = 15
    font_family = Hack
    position = 0, -65
    halign = center
    valign = center
}

# Subtexto hacker
label {
    monitor =
    text = cmd[update:1000] echo "[$(whoami)@$(hostname)] :: AUTH REQUIRED"
    color = rgba(7fffd4cc)
    font_size = 10
    font_family = Hack
    position = 0, -95
    halign = center
    valign = center
}

# Input principal
input-field {
    monitor =
    size = 320, 58
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(00ffccdd)
    inner_color = rgba(0a0f14bb)
    font_color = rgba(e8fffaff)
    fade_on_empty = false
    placeholder_text = <span foreground="##7fffd4">󰌆   Enter Password...</span>
    hide_input = false
    rounding = 14
    check_color = rgba(00ff99ee)
    fail_color = rgba(ff4477ee)
    checking_text = ACCESS AUTHORIZED...
    fail_text = <i>$FAIL <b>ACCESS DENIED</b></i>
    capslock_color = rgba(ffcc00ee)
    position = 0, 25
    halign = center
    valign = center
}

# Caja decorativa arriba del input
shape {
    monitor =
    size = 420, 240
    color = rgba(00000044)
    rounding = 22
    border_size = 2
    border_color = rgba(00ffd5aa)
    position = 0, 10
    halign = center
    valign = center
}