#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = waybar
exec-once = dunst
exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = eww daemon
exec-once = sleep 2 && eww open reloj
exec-once = sleep 2 && eww open stats
exec-once = sleep 2 && eww open network
exec-once = sleep 4 && eww open byte_window
exec-once = sleep 2 && mpvpaper -o "no-audio loop" '*' ~/wallpaper/fondomov/wallpaper8.mp4 &
exec-once = sleep 6 && eww reload
exec-once = sleep 3 && pkill blueman-applet
