
# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 6
    gaps_out = 20
    border_size = 1
    
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(c084fcff) rgba(7c3aedff) rgba(4c1d95ff) 60deg
    col.inactive_border = rgba(2a203388)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}