##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule = match:class firefox, idle_inhibit always

windowrule = match:class vlc, idle_inhibit always

windowrule = match:class mpv, idle_inhibit always

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule = match:class ^(GLava)$, no_initial_focus on, pin on, opacity 0.55, float on, size 100% 22%, move 0 78%, border_size 0, decorate off
windowrule = match:class ^(GLava)$, workspace special silent

windowrule = float on, match:class ^(kitty)$
windowrule = size 78% 75%, match:class ^(kitty)$
windowrule = center on, match:class ^(kitty)$
windowrule = opacity 0.95 override 0.90 override, match:class ^(kitty)$
